# Generated by Django 4.0.4 on 2022-05-19 06:37

from django.db import migrations, models
import django.db.models.deletion
import stocksapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(blank=True, default=stocksapp.models.Account.generate_account_num, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('cashBalance', models.FloatField(default=50000.0)),
                ('overallValue', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeDate', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.FloatField()),
                ('buyOrSell', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('cashPrice', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.FloatField()),
                ('avgPricePerShare', models.FloatField()),
                ('currentValue', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.account')),
            ],
        ),
    ]
