# Generated by Django 4.0.4 on 2022-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='currentValue',
            field=models.FloatField(default=0.0),
        ),
    ]
